// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6w6zatzhIDT03k4aaYGqMvPnlIfkz244',
    appId: '1:985699191779:web:92e0eb59dad2be40b9aed6',
    messagingSenderId: '985699191779',
    projectId: 'dor-app-d5544',
    authDomain: 'dor-app-d5544.firebaseapp.com',
    storageBucket: 'dor-app-d5544.appspot.com',
    measurementId: 'G-D7RVPK84JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeC-Sl2ONTdEYIWvnqGuHOPzAkvREcLbg',
    appId: '1:985699191779:android:edd6c793ccc950c2b9aed6',
    messagingSenderId: '985699191779',
    projectId: 'dor-app-d5544',
    storageBucket: 'dor-app-d5544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA2E7wBts3MrRA1nVE0YrV-dQLf0SeCyw',
    appId: '1:985699191779:ios:14ca520a3dbccbd7b9aed6',
    messagingSenderId: '985699191779',
    projectId: 'dor-app-d5544',
    storageBucket: 'dor-app-d5544.appspot.com',
    iosClientId: '985699191779-7qfcctas87sidpdr08cl38ji84u592uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA2E7wBts3MrRA1nVE0YrV-dQLf0SeCyw',
    appId: '1:985699191779:ios:14ca520a3dbccbd7b9aed6',
    messagingSenderId: '985699191779',
    projectId: 'dor-app-d5544',
    storageBucket: 'dor-app-d5544.appspot.com',
    iosClientId: '985699191779-7qfcctas87sidpdr08cl38ji84u592uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorApp',
  );
}
